### ISSUE TITLE
Question : Ebook Solution and downloadable  student files for Java Programming by Joyce ferrell 

### ISSUE THREAD

**Issue by nonefornothing** [mblack1/Java-Files#1]
You have downloadable  student files and Solution for this book ?

**Comment by nonefornothing** [comment]
Update: i found downloadable  student files in this url : https://www.cengage.com/cgi-wadsworth/course_products_wp.pl?fid=M63&product_isbn_issn=9781285856919&chapter_number=0&resource_id=21&altname=Student%20Data%20Files

**Comment by mattsblack** [comment]
I just added all of the student files to download.
